# Site settings
title: Elisio Filho
email: elisionfilho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bussinessman & Entrepreneur. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: netinhufilho
github_username:  netinhufilho

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num"
